### ISSUE TITLE
multi-lingual support

### ISSUE THREAD

**Issue by lmballinger** [psu-libraries/cho-req#52] opened 2016-03-30 15:22 UTC
As an end user,
I need the descriptions (metadata) for objects to display accurately no matter what language or script they are in, 
so that important information about the objects isn't lost because it can't display properly.

[LB - I'm not sure from the issues list what was meant by multi-lingual support so I wrote it focusing on display, rather than searching.]

**Comment by ntallman** [comment] 2017-07-19 18:53
Closing, duplicate of #93.

**Closed by ntallman** 2017-07-19 18:53 UTC
Labels: discovery, enhancement, question, user
