### ISSUE TITLE
links to file names

### ISSUE THREAD

**Issue by lmballinger** [psu-libraries/cho-req#65] opened 2016-03-30 18:05 UTC
[LB - Okay, I don't even have a guess for this one. Links in the repository record (or record-like thing)? To files... where?]

**Comment by kestlund** [comment] 2016-05-09 16:19
Solved by storing full resolutions linked with derivatives and metadata in Fedora.

**Comment by ntallman** [comment] 2017-07-19 18:23
Closing this. No consensus on what was intended. File should be linked automatically.

**Closed by ntallman** 2017-07-19 18:23 UTC
Labels: cataloger, question, ready
