### ISSUE TITLE
geo coordinates search

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/cho-req#32] opened 2016-02-23 19:13 UTC
As a user,
I would like to be able to search objects by location,
So that I may contextualize my search results by coordinates/location.

**Comment by ntallman** [comment] 2017-06-09 19:06
@DanCoughlin Did you mean enter a query like (Dubois, PA) or did you mean an interactive map with the content plotted and drill-down map searching?

**Comment by ntallman** [comment] 2017-07-12 16:21
Duplicate of #109, which is more articulated. Closing this version.

**Closed by ntallman** 2017-07-12 16:21 UTC
Labels: collections, community priority, discovery, enhancement, question, user
